### ISSUE TITLE
第一个目标点点在编队正右方，出现问题

### ISSUE THREAD

**Issue by shirley033** [ZJU-FAST-Lab/Swarm-Formation#10]
![2022-07-05 15-44-39 的屏幕截图](https://user-images.githubusercontent.com/45134715/177276663-d140d2e1-b04c-4530-b89e-c9baeb170005.png)
四架飞机不动，代码没有改。

**Comment by SamuraiChamploo** [comment]
这是超出地图范围导致的问题
