### ISSUE TITLE
在没有障碍的时候，无人机会转圈圈或大波浪

### ISSUE THREAD

**Issue by shirley033** [ZJU-FAST-Lab/Swarm-Formation#11]
![2022-07-05 15-48-42 的屏幕截图](https://user-images.githubusercontent.com/45134715/177277665-2f7c8433-9b04-468d-813d-7f111096a293.png)
为什么不能直线过去？每个点都是在无人机抵达上一个目标点才发布的。

**Comment by SamuraiChamploo** [comment]
因为第一次轨迹规划时，不同无人机之间有时间差异，所以初始时队形并不完全收敛，需要飞一小段距离才可以

**Comment by shirley033** [comment]
这样哦，感谢！
