### ISSUE TITLE
运行仿真测试时其中一个agent停止不动，然后电脑内存爆掉死机

### ISSUE THREAD

**Issue by CharlChc** [ZJU-FAST-Lab/Swarm-Formation#13]
作者您好！在多台电脑上运行仿真测试时都发现在到达一个目标点后再发布新的目标点后，集群中会有一个到两个agent停止不动，其余agents继续执行规划轨迹，然后电脑死机。通过系统监控发现内存爆掉。请问大家是否遇到过同样的问题？应该如何解决？ 感谢！

**Comment by SamuraiChamploo** [comment]
请问你有进行什么修改吗?
