### ISSUE TITLE
hummingbird.skeleton

### ISSUE THREAD

**Issue by TUzizi** [ZJU-FAST-Lab/Swarm-Formation#14]
[ERROR] [1679322504.115688710]: Error retrieving file [file:///home/tutu/Swarm-Formation/src/Utils/odom_visualization/meshes/hummingbird.skeleton]: Couldn't open file /home/tutu/Swarm-Formation/src/Utils/odom_visualization/meshes/hummingbird.skeleton

I need your help! Where could I find the file hummingbird.skeleton?
And the UAVs do not move after I set the 2D goal. I have no idea how to do the debug.
![image](https://user-images.githubusercontent.com/105049539/226376330-a8ae3a46-fd69-42c6-8b93-1120e6851b56.png)

![image](https://user-images.githubusercontent.com/105049539/226376428-5448fee4-e386-4471-9800-8f9dba778d61.png)

![image](https://user-images.githubusercontent.com/105049539/226376538-e6c8ac1e-74f7-4407-b828-7157ff25234f.png)

Thanks.

**Comment by SamuraiChamploo** [comment]
Maybe you use the wrong target_type_ as shown below:

![1679991796138](https://user-images.githubusercontent.com/25478757/228175176-7fb1b394-a0c1-4348-a375-924a016e3967.png)

which means the target_type_ =3 is invalid!

And the warning about hummingbird.skeleton is not important

**Comment by SamuraiChamploo** [comment]
It seems that the questioner has no further questions, so let me close the issue
