### ISSUE TITLE
Question on maps

### ISSUE THREAD

**Issue by smarnav2904** [ZJU-FAST-Lab/Swarm-Formation#15]
Could it be possible to run your code on custom predesigned enviroments instead of random ones? Some of your packages depend on "map_generator" so removing it it's not an option but would like to tun some metrics for a paper.

**Comment by SamuraiChamploo** [comment]
Hello, it is theoretically feasible. Our formation algorithm has no special requirements for the map representation. In the paper, for convenience, we chose to generate the ESDF field in the map_generator to provide obstacle avoidance information. You can replace the above scheme with your desired map representation and obstacle avoidance gradient generation method

**Comment by smarnav2904** [comment]
Thank you very much for your response, I managed to change it and runs pretty smoothly. Soon I'll be publishing my final degree project and obviously I'll mention your amazing work with this project.

**Comment by SamuraiChamploo** [comment]
This is cool. I'm looking forward to your work. Please let me know~
