### ISSUE TITLE
您好~我想拜读您的这组代码

### ISSUE THREAD

**Issue by lgl-960709** [ZJU-FAST-Lab/Swarm-Formation#2]
您好,不知是否有荣幸可以拜读您的这个代码,想咨询一下您何时开源这项工程.万分感谢

**Comment by SamuraiChamploo** [comment]
the code is open-sourced now, so I close this issue

**Comment by lgl-960709** [comment]
Thank you very much for your reply and guidance. Is this running on Ubuntu 18.04 please? I look forward to hearing from you.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZJU-FAST-Lab/Swarm-Formation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月12日(星期二) 晚上11:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZJU-FAST-Lab/Swarm-Formation] 您好~我想拜读您的这组代码 (Issue #2)





 
the code is open-sourced now, so I close this issue
