### ISSUE TITLE
Motion target interference

### ISSUE THREAD

**Issue by jijiking-hh** [ZJU-FAST-Lab/Swarm-Formation#22]
你好，请问在实现多机规划仿真时，您的环境避障用到了ESDF图，而多无人机的避障和编队则是通过通信获取信息，但获取点云数据的时候应该会包含旁边运动的无人机，请问如何在生成环境ESDF图的时候避免身边运动无人机的干扰呢？理论上ESDF环境避障和通信获取其他无人机轨迹信息应该独立。
     希望作者有空能够解答一下，非常感谢！

**Comment by SamuraiChamploo** [comment]
你好，很抱歉这么晚才回复。

首先关于多机规划仿真里ESDF的问题，如果你仔细看代码结构就会发现，仿真里的ESDF是每个无人机独立建图的，建图的输入是来自于全局地图点云根据无人机位姿返回的局部点云，这个输入里面是不包含其他无人机的点云，所以在仿真中并不会出现你担心的问题。

但上述问题在真实环境中是会出现的，即生成EDSF时，周围的无人机可能会干扰建图，这个问题比较复杂，我还是从输入的角度来解释，真实环境中，ESDF输入的点云来自概率栅格地图，在无人机集群一起飞行时，运动的无人机点云不会被当做静态障碍物建到点云地图中，所以也不会影响ESDF，但如果停下来时，无人机作为静态障碍物会别识别为障碍物。

更进一步，这个问题可以被归纳为如何将周围协作的无人机同障碍物区分开来，这里我推荐你去看论文[ego-swarm](https://ieeexplore.ieee.org/abstract/document/9561902)
里面有相关内容可以参考：
![Uploading 捕获.PNG…]()

**Comment by jijiking-hh** [comment]
非常感谢您的解答,确实,通过你们的simuolator可以避免这个问题.但我的仿真环境暂时还是基于PX4+gazebo的,因此我可能更感兴趣实际避免干扰的方式.
所以对于您上文第二段所提到的运动时的无人机点云不会被当成静态障碍建到esdf图中,是指您所使用的建图算法已经包含了移动点云分割并滤出的功能还是指以上操作是基于ego-swarm的agent remova(drone detect)模块实现的?
再次感谢您的回答!

**Comment by SamuraiChamploo** [comment]
“使用的建图算法已经包含了移动点云分割并滤出的功能”

是的，我们提供的建图是概率栅格地图，移动较快的物体点云不会立刻被当做障碍物。

不过这个方法并不是专门用于移除无人机点云的，所以更推荐“基于ego-swarm的agent remova”
