### ISSUE TITLE
在仿真中如何增大飞行器的视野？

### ISSUE THREAD

**Issue by GSKun1** [ZJU-FAST-Lab/Swarm-Formation#27]

**Comment by SamuraiChamploo** [comment]
![image](https://github.com/ZJU-FAST-Lab/Swarm-Formation/assets/25478757/3a5892bd-be19-4e0a-9257-1cd55cc5771b)

**Comment by GSKun1** [comment]
谢谢，我修改了感知视野以及局部地图更新范围等参数后，扩大了飞行器的视野
