### ISSUE TITLE
变换队形

### ISSUE THREAD

**Issue by robot-WT** [ZJU-FAST-Lab/Swarm-Formation#29]
我想实现像视频里的心形队形，或者字母队形，应该如何配置呢，期待您的回答。

**Comment by robot-WT** [comment]
我知道了

**Comment by robot-WT** [comment]
我想在运动的时候能够变换队形，所以写了一个python程序程序读取normal_hexagon.yaml（我新建了），此时formation_type也变为了我预设的值，但运动过程中的队形也就没有变。所以我修改了程序，我在输出reached goal的前面重新设置参数ploy_traj_opt_->setParam(nh);但会导致程序报错，您能帮忙看看是什么问题吗？万分感谢

**Comment by AnonChihayaaa** [comment]
Do you solve this yet? I'm also focusing on changing the formation during flight but have trouble getting it work. Can you share how to implement this?

**Comment by robot-WT** [comment]
Considering that the formation transformation is completed during sports, we find its formation definition function setDesiredFormation and find that it is initialized when the class is instantiated. Additional calls will cause an error. A loop function is needed to determine when the formation transformation is completed, based on formation_type. Determine formation changes. Considering the communication mechanism of ROS, we know that rosmaster manages all parameters in ros, which is equivalent to a database. We only need to complete the overloading of parameters and complete the formation transformation in the instantiated loop execution function. Since the callback function of ros is repeatedly executed in the program, we found a callback function formationWaypointCallback to overload the formation parameter.
