### ISSUE TITLE
无人机架数达到100架时，编队飞行避障效果会怎么样

### ISSUE THREAD

**Issue by dlml** [ZJU-FAST-Lab/Swarm-Formation#4]

**Comment by SamuraiChamploo** [comment]
首先与计算量，目前台式机仅支持15架编队的避障仿真

**Comment by dlml** [comment]
有考虑过用平均场去做吗 或者说可以利用随机地图在线的强化学习去做吗

**Comment by dlml** [comment]
15架编队效果相比7架是不是要差一些？

**Comment by SamuraiChamploo** [comment]
> 有考虑过用平均场去做吗 或者说可以利用随机地图在线的强化学习去做吗

据我所知，暂时没有这类方法可以达到与该工作类似的效果，所以暂未考虑上述方法

**Comment by SamuraiChamploo** [comment]
> 15架编队效果相比7架是不是要差一些？

随着集群数量增多，分布式系统的编队效果变差是必然的。

**Comment by dlml** [comment]
好吧 我理解的swarm应该是100架以上
