### ISSUE TITLE
如何设置一个目标点序列，使得可以完成多段路径规划

### ISSUE THREAD

**Issue by LNTisNotaTree** [ZJU-FAST-Lab/Swarm-Formation#7]
我不知道是否有方法可以设置多个目标点，然后使得路径规划分段进行，目前我只能通过设置多个waypoints进行一段轨迹整体的路径规划，非常感谢！

**Comment by LNTisNotaTree** [comment]
补充：如下图，目前当我希望可以以红色路径行进时却只能得到蓝色的轨迹。祝工作顺利！
![已导入的文件 (4)](https://user-images.githubusercontent.com/62611670/167621853-d8d47193-68d7-4dfe-bef4-06183303422c.png)

**Comment by SamuraiChamploo** [comment]
可以参考这个解答[https://github.com/ZJU-FAST-Lab/Swarm-Formation/issues/6#issuecomment-1120653118](url)
