### ISSUE TITLE
请问集群行进过程中没有撞到障碍，但突然卡死一个飞机的可能原因是什么？

### ISSUE THREAD

**Issue by LNTisNotaTree** [ZJU-FAST-Lab/Swarm-Formation#9]

**Comment by SamuraiChamploo** [comment]
你这个问题是偶尔出现还是一直出现？

你是否自己修改过ego_replan_fsm.cpp中的状态机，因为你的报错信息很奇怪，这个报错只会在第一次规划失败时反复出现，但你的无人机显然已经运动了一段距离

**Comment by SamuraiChamploo** [comment]
看起来这个问题并没有继续困扰你，so I close this issue
